### ISSUE TITLE
Callbacks for NightlyJobs

### ISSUE THREAD

**Issue by coldtobi** [moisseev/BackupPC#1]
As just mailed to backuppc-devel, here's a patch to add support for an callback to be run before/after NightlyJob.

The patch is against 3.3.0

https://gist.github.com/coldtobi/8f5556a4c0f5e1d38125

Text to backuppc-devel:

Here's a small patch against 3.3.0 which enhances BackupPC callback
methods for nightly jobs: It adds the possiblity to call those jobs,
NightlyPreUserCmd
NightlyPostUserCmd
, called before and after the NightlyRun. 

(My use-case is that I have flashcache running on the Pool's partition
and to avoid cache-poisoning by the NightlyJobs I deactivate caching
during backup and nightly-jobs. I can provide those scripts on request,
just email me.) 
## 

tobi

**Comment by moisseev** [comment]
Reopened as backuppc/backuppc#5
